-- Q1. What is the total revenue generated by male vs. female customers?
Select
	gender,
	sum(purchase_amount) AS total_revenue
From public.customer
Group by gender
Order By total_revenue DESC;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
Select
	customer_id,
	purchase_amount
From public.customer
Where discount_applied = 'Yes'
	AND purchase_amount >= (
	Select AVG(purchase_amount)
	From public.customer
);

-- Q3. Which are the top 5 products with the highest average review rating?
Select
	item_purchased,
	Round(AVG(review_rating::numeric),2) AS average_product_rating
From public.customer
Group by item_purchased
Order By AVG(review_rating) DESC
Limit 5;

-- Q4. How do average purchase amounts compare between Standard and Express Shipping?
Select
	shipping_type,
	ROUND(AVG(purchase_amount),2) AS average_purchase_amount
From public.customer
Where shipping_type IN ('Standard','Express')
Group By shipping_type;

-- Q5. Do subscribed customers spend more than non-subscribers? 
/* This question is slightly more advanced because we're comparing three things:
Number of customers
Average spend
Total revenue */
Select
	subscription_status,
	COUNT(customer_id) AS total_customers,
	ROUND(AVG(purchase_amount),2) AS avg_spend,
	ROUND(SUM(purchase_amount),2) AS total_revenue
From public.customer
Group By subscription_status
Order By total_revenue DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
Select
	item_purchased,
	ROUND(100.0 * SUM(
	CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
From public.customer
Group By item_purchased
Order By discount_rate DESC
Limit 5;

-- Q7. Segment customers into New, Returning and Loyal based on previous purchases
/* Here we're defining 
Previous Purchases = 1
→ New
Previous Purchases = 2–10
→ Returning
Previous Purchases > 10
→ Loyal */
With customer_type AS (
	Select
		customer_id,
		previous_purchases,
		Case
			When previous_purchases = 1 Then 'New'
			When previous_purchases BETWEEN 2 and 10 Then 'Returning'
			Else 'Loyal'
		End as customer_segment
	From public.customer
)
Select
	customer_segment,
	COUNT(*) AS number_of_customers
From customer_type
Group by customer_segment
Order By number_of_customers DESC;

-- Q8. What are the top 3 most purchased products within each category?
With item_counts AS (
	Select
		category,
		item_purchased,
		COUNT(customer_id) AS total_orders,
		ROW_NUMBER() Over (
				Partition By category
				Order By Count(customer_id) DESC
		) AS item_rank
	From public.customer
	Group By category, item_purchased
)
Select
	item_rank,
	category,
	item_purchased,
	total_orders
From item_counts
Where item_rank <= 3
Order By category, item_rank;

-- Q9. Are repeat buyers more likely to subscribe?
/* The question defines repeat buyers as customers with: previous_purchases > 5 */
Select 
	subscription_status,
	COUNT(customer_id) AS repeat_buyers
From public.customer
Where previous_purchases > 5
Group By subscription_status;

-- Q10. What is the revenue contribution of each age group?
Select
	age_group,
	SUM(purchase_amount) AS total_revenue
From public.customer
Group By age_group
Order By total_revenue DESC;